# Playing around and discovering tensors in pytorch

In [1]:
import torch

In [2]:
# scalar
scalar = torch.tensor(7)

In [3]:
scalar

tensor(7)

In [4]:
type(scalar)

torch.Tensor

In [5]:
scalar.ndim

0

In [6]:
scalar.shape

torch.Size([])

In [7]:
vector = torch.tensor([7, 7])

In [8]:
# vector.item() RUNTIME ERROR

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
MATRIX = torch.tensor([[7, 8],
                       [3, 4]])
MATRIX

tensor([[7, 8],
        [3, 4]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
TENSOR = torch.tensor([[[1, 2, 3, 5],
                        [4, 5, 6, 8],
                        [4, 6, 9, 0]],
                       [[1, 2, 3, 5],
                        [7, 8, 9, 8],
                        [9, 8, 7, 6]]])

In [15]:
TENSOR.ndim # ndim can be interpretated as the amount of square brackets

3

In [16]:
TENSOR.size()

torch.Size([2, 3, 4])

In [17]:
TENSOR[1]

tensor([[1, 2, 3, 5],
        [7, 8, 9, 8],
        [9, 8, 7, 6]])

In [18]:
TENSOR[1].ndim, TENSOR[1].size()

(2, torch.Size([3, 4]))

In [19]:
TENSOR.size(), TENSOR.shape

(torch.Size([2, 3, 4]), torch.Size([2, 3, 4]))

### Random tensors

In [20]:
random_tensor = torch.rand(3, 2, 4)
random_tensor

tensor([[[0.7377, 0.3170, 0.8980, 0.1505],
         [0.3738, 0.1827, 0.7926, 0.3698]],

        [[0.2376, 0.7220, 0.6504, 0.7543],
         [0.0103, 0.3600, 0.6763, 0.3323]],

        [[0.6618, 0.2263, 0.2286, 0.4342],
         [0.7316, 0.3693, 0.7987, 0.1923]]])

In [21]:
image_tensor = torch.rand(size=(3, 224, 224)) # colour channels, height, width, colour channels

In [22]:
image_tensor.ndim, image_tensor.size()

(3, torch.Size([3, 224, 224]))

In [23]:
image_tensor

tensor([[[0.0024, 0.4159, 0.2516,  ..., 0.6269, 0.1575, 0.4759],
         [0.4459, 0.6739, 0.8544,  ..., 0.2257, 0.6672, 0.5189],
         [0.4087, 0.5318, 0.6860,  ..., 0.9083, 0.0482, 0.4578],
         ...,
         [0.8913, 0.0717, 0.8473,  ..., 0.2304, 0.5575, 0.4818],
         [0.4923, 0.5550, 0.7543,  ..., 0.6684, 0.8061, 0.2795],
         [0.1391, 0.4036, 0.1905,  ..., 0.3406, 0.5398, 0.2632]],

        [[0.5609, 0.3225, 0.5967,  ..., 0.8480, 0.6877, 0.9617],
         [0.1380, 0.0763, 0.2292,  ..., 0.2278, 0.7945, 0.1854],
         [0.1535, 0.4595, 0.2330,  ..., 0.6550, 0.3522, 0.8898],
         ...,
         [0.8989, 0.7590, 0.5460,  ..., 0.4192, 0.3279, 0.5126],
         [0.9357, 0.4283, 0.1551,  ..., 0.2682, 0.9494, 0.7440],
         [0.2353, 0.7315, 0.8395,  ..., 0.6117, 0.0784, 0.8475]],

        [[0.2254, 0.2522, 0.2831,  ..., 0.2350, 0.8731, 0.8597],
         [0.1157, 0.0076, 0.5651,  ..., 0.8402, 0.8316, 0.8502],
         [0.2552, 0.1415, 0.2169,  ..., 0.3284, 0.3287, 0.

In [24]:
random_tensor * 255

tensor([[[188.1145,  80.8459, 228.9774,  38.3800],
         [ 95.3304,  46.5806, 202.1194,  94.3004]],

        [[ 60.6005, 184.0982, 165.8510, 192.3586],
         [  2.6326,  91.8038, 172.4465,  84.7385]],

        [[168.7702,  57.7101,  58.3040, 110.7158],
         [186.5600,  94.1741, 203.6734,  49.0485]]])

### Zeros and ones tensors

In [25]:
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
torch.zeros(3, 4) * torch.rand(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
torch.ones(3, 4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
torch.arange(10) 

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
torch.arange(0, 10) + 1

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
ten_zeros = torch.zeros_like(torch.arange(0, 10))

In [31]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
torch.zeros(torch.arange(10).size(), dtype=torch.int32)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)

### Tensor datatypes

In [33]:
int_tensor = torch.tensor([3, 6, 9], dtype=None)
int_tensor

tensor([3, 6, 9])

In [34]:
int_tensor.dtype

torch.int64

### Tensor datatypes is one of the 3 big errors you'll run into with PyTorch.
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [35]:
 gpu_tensor = torch.rand(size=(3, 2), device='cuda')

In [36]:
cpu_tensor = torch.rand(size=(3, 2), device='cpu')

In [37]:
# gpu_tensor * cpu_tensor 
# 
# RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [38]:
random_tensor = torch.rand(size=(3, 2))

In [39]:
random_tensor.device

device(type='cpu')

In [40]:
random_tensor * cpu_tensor

tensor([[0.0987, 0.0067],
        [0.2118, 0.0068],
        [0.2164, 0.1384]])

In [41]:
cpu_tensor

tensor([[0.4727, 0.0086],
        [0.4683, 0.1933],
        [0.3355, 0.8679]])

In [42]:
(cpu_tensor * 100).type(torch.int32)

tensor([[47,  0],
        [46, 19],
        [33, 86]], dtype=torch.int32)

In [43]:
rand_int = (torch.rand(size=(3, 2)) * 100).type(torch.int32)
rand_int

tensor([[76, 81],
        [83, 37],
        [74, 46]], dtype=torch.int32)

In [44]:
rand_float = torch.rand(size=(3, 2))
rand_float

tensor([[0.7744, 0.8779],
        [0.8864, 0.6302],
        [0.4989, 0.2942]])

In [45]:
rand_float.dtype

torch.float32

In [46]:
rand_float * rand_int

tensor([[58.8530, 71.1063],
        [73.5685, 23.3172],
        [36.9176, 13.5344]])

In [47]:
rand_int * rand_float

tensor([[58.8530, 71.1063],
        [73.5685, 23.3172],
        [36.9176, 13.5344]])

In [48]:
rand_int.max()

tensor(83, dtype=torch.int32)

In [49]:
rand_int.to("cuda:0")

tensor([[76, 81],
        [83, 37],
        [74, 46]], device='cuda:0', dtype=torch.int32)

In [50]:
gpu_tensor

tensor([[0.9541, 0.4807],
        [0.1265, 0.1007],
        [0.8331, 0.5458]], device='cuda:0')

### Operations

In [51]:
rand_int

tensor([[76, 81],
        [83, 37],
        [74, 46]], dtype=torch.int32)

In [52]:
rand_int + 1

tensor([[77, 82],
        [84, 38],
        [75, 47]], dtype=torch.int32)

In [53]:
rand_int + rand_int

tensor([[152, 162],
        [166,  74],
        [148,  92]], dtype=torch.int32)

In [54]:
rand_int * 2

tensor([[152, 162],
        [166,  74],
        [148,  92]], dtype=torch.int32)

In [55]:
rand_int / 10

tensor([[7.6000, 8.1000],
        [8.3000, 3.7000],
        [7.4000, 4.6000]])

In [56]:
(rand_int / 10).dtype

torch.float32

### Matrix multiplication

In [57]:
matrix_1 = (torch.rand(3, 4) * 100).type(torch.int32)
matrix_1

tensor([[56, 53,  1, 84],
        [89, 22, 85,  2],
        [50, 34, 41, 83]], dtype=torch.int32)

In [58]:
matrix_2 = (torch.rand(3, 4) * 100).type(torch.int32)
matrix_2

tensor([[44,  4, 29, 63],
        [99, 84, 20, 18],
        [48,  2, 85, 81]], dtype=torch.int32)

In [59]:
matrix_1 * matrix_2

tensor([[2464,  212,   29, 5292],
        [8811, 1848, 1700,   36],
        [2400,   68, 3485, 6723]], dtype=torch.int32)

In [60]:
matrix_1 @ matrix_2

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x4 and 3x4)

In [ ]:
matrix_3 = (torch.rand(4, 3) * 100).type(torch.int32)
matrix_3

In [ ]:
matrix_1 @ matrix_3

In [ ]:
matrix_1.matmul(matrix_3)

In [ ]:
torch.tensor([1, 2, 3]) @ torch.tensor([1, 2, 3])

In [ ]:
%%time
ejemplo = torch.tensor([1, 2, 3])
ejemplo_2 = torch.tensor([1, 2, 3])

suma = sum(i * j for i, j in zip(ejemplo, ejemplo_2))
print(suma)

In [ ]:
%%time
ejemplo = torch.tensor([1, 2, 3])
ejemplo_2 = torch.tensor([1, 2, 3])

value = 0
for i in range(len(ejemplo)):
    value += ejemplo[i] * ejemplo_2[i]
print(value)

In [ ]:
%%time 
ejemplo = torch.tensor([1, 2, 3])
ejemplo_2 = torch.tensor([1, 2, 3])

value = ejemplo @ ejemplo_2
print(value)

In [ ]:
matrix_2

In [ ]:
matrix_2.shape

In [ ]:
matrix_2.T

In [ ]:
matrix_2 @ matrix_2.T

### Tensor agregation (min, max, sum, etc)

In [ ]:
x = torch.arange(0, 100, 10).type(torch.float32)
x

In [61]:
x.min(), x.max(), x.mean(), x.std()

NameError: name 'x' is not defined

### mean and std require the type float

In [62]:
x.argmin(), x.argmax()

NameError: name 'x' is not defined

In [63]:
matrix_2

tensor([[44,  4, 29, 63],
        [99, 84, 20, 18],
        [48,  2, 85, 81]], dtype=torch.int32)

In [64]:
matrix_2.reshape(1, 3, 4)

tensor([[[44,  4, 29, 63],
         [99, 84, 20, 18],
         [48,  2, 85, 81]]], dtype=torch.int32)

In [65]:
matrix_2.reshape(2, 2, 3)

tensor([[[44,  4, 29],
         [63, 99, 84]],

        [[20, 18, 48],
         [ 2, 85, 81]]], dtype=torch.int32)

In [66]:
matrix_2.reshape(12, 1)

tensor([[44],
        [ 4],
        [29],
        [63],
        [99],
        [84],
        [20],
        [18],
        [48],
        [ 2],
        [85],
        [81]], dtype=torch.int32)

In [67]:
matrix_2.reshape(shape=(4, 3))

tensor([[44,  4, 29],
        [63, 99, 84],
        [20, 18, 48],
        [ 2, 85, 81]], dtype=torch.int32)

In [68]:
matrix_2

tensor([[44,  4, 29, 63],
        [99, 84, 20, 18],
        [48,  2, 85, 81]], dtype=torch.int32)

In [69]:
test_matrix = matrix_2.view(4, 3)

In [70]:
test_matrix

tensor([[44,  4, 29],
        [63, 99, 84],
        [20, 18, 48],
        [ 2, 85, 81]], dtype=torch.int32)

In [71]:
matrix_2

tensor([[44,  4, 29, 63],
        [99, 84, 20, 18],
        [48,  2, 85, 81]], dtype=torch.int32)

In [72]:
test_matrix[1, 2] = 0
test_matrix

tensor([[44,  4, 29],
        [63, 99,  0],
        [20, 18, 48],
        [ 2, 85, 81]], dtype=torch.int32)

In [73]:
matrix_2

tensor([[44,  4, 29, 63],
        [99,  0, 20, 18],
        [48,  2, 85, 81]], dtype=torch.int32)

### .view() points at the same memory space as the original 

In [74]:
matrix_2[0, 0] = 999
test_matrix

tensor([[999,   4,  29],
        [ 63,  99,   0],
        [ 20,  18,  48],
        [  2,  85,  81]], dtype=torch.int32)

In [75]:
matrix_2.unsqueeze(dim=0)

tensor([[[999,   4,  29,  63],
         [ 99,   0,  20,  18],
         [ 48,   2,  85,  81]]], dtype=torch.int32)

In [76]:
matrix_2.unsqueeze(dim=1)

tensor([[[999,   4,  29,  63]],

        [[ 99,   0,  20,  18]],

        [[ 48,   2,  85,  81]]], dtype=torch.int32)

In [77]:
matrix_2.unsqueeze(dim=1).shape

torch.Size([3, 1, 4])

### The permute method just changes the order of the dimensions

In [78]:
image_tensor = torch.rand(size=(224, 224, 3))

In [79]:
image_tensor.shape

torch.Size([224, 224, 3])

In [80]:
image_tensor.permute(2, 0, 1).shape

torch.Size([3, 224, 224])

### permute returns a view, so remember that both of the tensors point to the same place in memory                                                                                                  

In [81]:
matrix = torch.arange(1, 10).reshape(1, 3, 3)

In [82]:
matrix, matrix.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [83]:
matrix[0, 0, 0]

tensor(1)

In [84]:
matrix[0, :, 1]

tensor([2, 5, 8])

In [85]:
matrix[0, :, 1].unsqueeze(dim=1)

tensor([[2],
        [5],
        [8]])

### Pytorch tensors with numpy

In [86]:
import numpy

In [87]:
array = numpy.arange(1, 10)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
tensor = torch.from_numpy(array)
tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
tensor.dtype

torch.int64

In [90]:
array.dtype

dtype('int64')

In [91]:
numpy.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [92]:
torch.linspace(0, 1, 20)

tensor([0.0000, 0.0526, 0.1053, 0.1579, 0.2105, 0.2632, 0.3158, 0.3684, 0.4211,
        0.4737, 0.5263, 0.5789, 0.6316, 0.6842, 0.7368, 0.7895, 0.8421, 0.8947,
        0.9474, 1.0000])

In [93]:
array, tensor

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [94]:
array += 1
array, tensor

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [95]:
array = array + 1
array, tensor

(array([ 3,  4,  5,  6,  7,  8,  9, 10, 11]),
 tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [97]:
tensor.numpy().dtype

dtype('int64')

In [98]:
tensor.device

device(type='cpu')

In [99]:
tensor.to('cuda')

tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10], device='cuda:0')